// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mukqpwinqhdfffdkthcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11a3Fwd2lucWhkZmZmZGt0aGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjYxNTgsImV4cCI6MjA2MDE0MjE1OH0.CZaUCoWQhzktkm2ksDyyQbH4XW7RkjTSu5I3v88uNWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: false
  }
});